version: '3.8'

volumes:
  postgres-data:
  redis-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
    - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8025:8025" # MailHog web interface
      - "1025:1025" # SMTP server
